<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
/* @var $this Mage_Catalog_Block_Layer_State */
?>

<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
    <div class="currency">
        <h2>
            <span class="icon-ellipsis"></span>
            <?php echo $this->__('Currently Shopping by:') ?>
        </h2>
         <?php foreach ($_filters as $_filter): ?>
        
            <h3>
                <?php echo $this->__($_filter->getName()) ?> 
            </h3>
            <span class="value">
                <span class="icon-chevron-thin-left"></span>
                <?php echo $this->stripTags($_filter->getLabel()) ?>    
            </span>
                <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    if ($clearLinkUrl):
                ?>
                    <a  class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Previous') ?>"><?php echo $this->__('Previous') ?></a>
                    <a  class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
                <?php else: ?>
                    <a  class="btn-remove btn" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>">
                        <span class="icon-minus3"></span>        
                        <?php /* echo $this->__('Remove This Item') */ ?>
                    </a>
                <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
